INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('C''era una volta in america', 6, 1, 'C''era una volta in america colonna sonora', 'https://www.youtube.com/embed/nbFfHDOXDkY');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Il caffe della Peppina', 3, 1, 'Non si beve alla mattina ne col latte ne col te', 'https://www.youtube.com/embed/-xL2Y2HKEI8');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Le Tagliatelle di Nonna Pina', 3, 2, 'Son molto più efficaci di ogni vitamina', 'https://www.youtube.com/embed/HAzbZbjztbc');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Rimedio per il rafreddore', 4, 5, 'Sciroppo alle cipolle. - Questo rimedio viene considerato adatto per il raffreddore accompagnato da tosse. Sfrutta le proprietà antibatteriche e antinfiammatorie della cipolla e la capacità del miele di calmare la tosse. Può aiutare a disciogliere ed eliminare il muco. Potrete anche sostituire il miele con lo zucchero di canna integrale.', 'https://www.youtube.com/embed/jJtZ1nRo9wQ');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Corso di uncineto - maglia bassa', 1, 5, 'La maglia bassa è il punto più conosciuto. 
Facile e veloce da eseguire è indicato per capi modellati come giacche e gonne, nella lavorazione a jacquard e per rifinire margini di cucitura decorativi. 1. Eseguire una base di catenelle, puntare l''uncinetto nella seconda catenella (la prima sostituisce la prima maglia bassa della riga successiva), gettare il filo sull''unc. ed estrarre 1 maglia. Gettare nuovamente il filo sull''uncinetto.', 'https://www.youtube.com/embed/z0Wh4Y5fRq8');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Design dalla terra alla tavola', 2, 3, 'Design dalla terra alla tavola: a Treviso quattro giorni dedicati al bello e buono che produce il lavoro degli agricoltori e in particolare degli ortofrutticoltori. Quattro giorni di incontri e di dibattito, protagonisti gli studenti del corso di laurea in design industriale e multimedia. Soprattutto una bella mostra, nell''archivio di Stato, dove sono stati esposti i più brillanti progetti degli universitari, concepiti e realizzati per valorizzare i prodotti ortofrutticoli del territorio e presentarli beni sul mercato. Una festa di idee e di colori. Meravigliosi spunti per rendere belli e appetibili i radicchi, gli asparagi, i peperoni, le carote, le fragole; poi strumenti ergonomici per facilitare il lavoro dei coltivatori, come sarchiatori, guanti, stivali versatili, dotati di un''ampia gamma di accessori, spelucchini e altri attrezzi. Proposte, quindi, di grafica e di comunicazione, soluzioni festose di packaging, oggetti di uso quotidiano, kit da picnic, sporte e contenitori vari. E'' il domani agricolo intuito dai giovani, capaci con la freschezza delle loro idee di offrire cose nuove e belle altamente innovative e funzionali. Tra i tanti convegni, che si sono susseguiti nel corso della manifestazione, sempre molto frequentati, si ricordano in particolare â??La felicitÃ  del made in Italy: come arrivare là  dove l''Italia merita, protagonista Oscar Farinetti, ideatore di Eataly, e â??Good food, good future; Verso il futuro dell''alimentazione responsabile, relatori Cesare Bellà, consigliere delegato di OPO Veneto, Mascia Consorte, excellence club manager Wfp Italia, Fiamma Pratesi, Barilla Center for food and nutrition e Piero Sardo, presidente della Fondazione Slow food per la biodiversità.', 'https://www.youtube.com/embed/enD16BcOfgA');
INSERT INTO CARPEDIEM.POST (TITOLO, CATEGORIA, UTENTE, TESTO, MEDIA) 
	VALUES ('Prima guerra Mondiale', 5, 4, 'La prima guerra mondiale fu il risultato di un lungo periodo di tensioni tra le principali potenze europee. La Germania, in particolare, voleva imporsi come paese guida del continente, contrastata dall''Inghilterra e dalla Francia, desiderosa questa di una rivincita dopo la sconfitta del 1870. L''impero austro-ungarico e quello russo vedevano invece minacciata la loro integrità dalle richieste di indipendenza dei diversi popoli sottomessi. Il conflitto scoppiò dopo l''assassinio (28 giugno 1914) di Francesco Ferdinando, erede al trono d''Austria. L''Austria ne ritenne responsabile la Serbia, dichiarandole guerra. Il meccanismo delle alleanze fece entrare nel conflitto Gran Bretagna, Francia e Russia da un lato, e dall''altro Germania e Austria. L''Italia si mantenne per il momento, neutrale.
L''esercito tedesco cercò di cogliere di sorpresa la Francia con un rapido attacco sul fronte occidentale (agosto 1914). Invaso il Belgio neutrale, i Tedeschi penetrarono nel territorio nemico ma furono sconfitti nella battaglia della Marna. La guerra di movimento divenne così guerra di posizione, combattuta nelle trincee. Altre due grandi battaglie, a Verdun e sul fiume Somme (1916), lasciarono immutate le posizioni dei due eserciti. Intanto sul fronte orientale l''esercito tedesco occupava la Polonia.Nel maggio del 1915 anche l''Italia entrÃ² in guerra, a fianco di Francia e Inghilterra, dopo lunghi e accesi contrasti interni. Contrari all''intervento si erano dichiarati, con Giolitti, molti cattolici e socialisti. Favorevoli furono i nazionalisti ma anche molti democratici e socialisti riformisti, convinti che la guerra fosse necessaria per completare l''indipendenza nazionale con la conquista di Trento e Trieste.', 'https://www.youtube.com/embed/zlu7ZLqWlt4');
